clc;

instruments = {'Pianoforte','Electric Piano','Clavinet','Harpsichord',...
        'Vibraphone','Glockenspiel','Marimba','Xylophone','Pipe Organ',...
        'Hammond Organ','Accordion','Harmonica','Classic Guitar',...
        'Ukulele','Acoustic Guitar','Mandolin','Electric Guitar',...
        'Electric Bass','Violin','Viola','Cello','Contrabass',...
        'Harp','Timpani 23 Inches','Timpani 26 Inches', ...
        'Timpani 29 Inches', 'Timpani 32 Inches', 'Trumpet','Cornet',...
        'Trombone','Tuba','French Horn','Soprano Sax','Alto Sax','Tenor Sax',...
        'Baritone Sax','Oboe','English Horn','Bassoon (Fagotto)',...
        'Clarinet','Piccolo','Flute','Pan Flute','Recorder','Shakuhachi',...
        'Banjo','Shamisen','Koto','Sho','Japanese Percussion','Concert Drums',...
        'Rock Drums','Jazz Drums ','Percussion','Percussion','Percussion',...
        'Percussion','Soprano (Female)','Alto (Female)','Tenor (Male)',...
        'Baritone (Male)','Bass (Male)','R&B Vocal (Male)','R&B Vocal (Female)'};
    
keys = {'PF','EP','CV','HC','VI','GL','MB','XY','OR','HO','AC','HM', ...
        'CG','UK','AG','MD','EG','EB','VN','VL','VC','CB','HP',...
        'T1','T2','T3' ,'T4','TR','CR','TB','TU','HR','SS','AS','TS','BA','OB',...
        'EH','FG','CL','PC','FL','PN','RC','SH','BJ','SA','KT','SO','ND',...
        'BD','BD','BD','TM','BG','CO','CW','SP','AL','TN','BT','BS',...
        'VM','VF'};
    
unusedkeys = {'AL','BD','BG','BS','BT','CO','CW','GL','MB','ND',...
            'SP','T1','T2','TM','TN','VF','VI','VM','XY','T3','T4','CB','CG',...
            'CV','EP','HO','SH','SO','KT','SA'};
        
usedkeys = setdiff(keys,unusedkeys);        
        
map = containers.Map(keys,instruments);
mapmany = @(x) cellfun(@(y) map(y), x,'uniformoutput',false);


tax  = {'Martin',...
    'pizzicato.p-strings.guitars', mapmany({'AG','EG','EB'}),...
	'pizzicato.p-strings.others', mapmany({'BJ','HC','UK','MD','HP'}),...
    'pizzicato.piano', mapmany({'PF'}), ...
    'sustained.s-strings.violins', mapmany({'VN','VL'}), ...
	'sustained.s-strings', mapmany({'VC'}), ...
    'sustained.flute/piccolo', mapmany({'PC','FL','PN','RC'}), ...
    'sustained.reeds', mapmany({'CL','OR','OB','FG','AC','HM'}), ...
    'sustained.brass', mapmany({'TR','CR','TB','TU','HR','EH'}),...
	'sustained.brass.saxophones', mapmany({'BA','TS','AS','SS'})};

tax = Taxonomy(tax{:});
display(tax);

% TODO check all methods and properties

clearvars -except tax;

